package com.example.invoicemaker.Database;

public class Query {

    public static String SELECT_ALL_FROM_BUSINESS_INFORMATION = "SELECT * FROM BUSINESS_INFORMATION";
    public static String SELECT_ALL_FROM_CLIENTS = "SELECT * FROM CLIENTS";
    public static String SELECT_ALL_FROM_ITEMS = "SELECT * FROM ITEMS";
    public static String SELECT_ALL_FROM_SETTINGS = "SELECT * FROM SETTINGS";
    public static String SELECT_CATALOGS_BY_CLIENT = "SELECT * FROM CATALOG WHERE PAID_STATUS = ? AND TYPE = ? AND CLIENTS_ID = ?";
    public static String SELECT_CATALOG_BY_CLIENT = "SELECT SUM(TOTAL_AMOUNT) as TOTAL_AMOUNT, SUM(PAID) as PAID, COUNT(_id) as TOTAL_CATALOG  FROM CATALOG WHERE TYPE = ? AND CLIENTS_ID = ?";
    public static String SELECT_CATALOG_IMAGES = "SELECT * FROM CATALOG_IMAGES WHERE CATALOG_ID = ?";
    public static String SELECT_CREATION_DATE_FROM_INVOICES = "SELECT CREATED_AT FROM CATALOG";
    public static String SELECT_ESTIMATES_FROM_CATALOG = "SELECT * FROM CATALOG WHERE TYPE = 1";
    public static String SELECT_INVOICES_FROM_CATALOG = "SELECT * FROM CATALOG WHERE TYPE = 0";
    public static String SELECT_INVOICE_ITEMS_ASSOCIATED = "SELECT * FROM ITEMS_ASSOCIATED WHERE CATALOG_ID = ?";
    public static String SELECT_INVOICE_PAYMENTS = "SELECT * FROM PAYMENTS WHERE CATALOG_ID = ?";
    public static String SELECT_INVOICE_SHIPPING = "SELECT * FROM SHIPPING WHERE CATALOG_ID = ?";
    public static String SELECT_PAID_FROM_CATALOG = "SELECT * FROM CATALOG WHERE PAID_STATUS = ? AND TYPE = ?";
    public static String SELECT_SINGLE_CATALOG = "SELECT * FROM CATALOG WHERE _id = ?";
    public static String SELECT_SINGLE_CLIENT = "SELECT * FROM CLIENTS WHERE _id = ?";
}
